version: '3.8'
services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_db
    ports:
      - "3306:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net

  backend:
    build: ./backend
    container_name: sgu-backend
    image: server:1.0-sgu
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - sgu-net

  frontend:
    build: ./client
    container_name: sgu-frontend
    image: client:1.0-sgu
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - sgu-net

networks:
  sgu-net:
    driver: bridge

volumes:
  sgu-volume:
